linters:
  enable-all: true
  disable:
   - exhaustivestruct
   - nosnakecase
   - interfacer
   - deadcode
   - maligned
   - varcheck
   - structcheck
   - scopelint
   - ifshort
   - golint
   - inamedparam
   - depguard
   - tagliatelle
   - exhaustruct
linters-settings:
  funlen:
    lines: 100
    statements: 50