dataBase:
  dbHost: "127.0.0.1"
  dbPort: "5432"
  dbName: "exachange_rates"
  dbUser: "postgres"
  dbPassword: "7777777"

host:
  hostPort: ":8080"

apiKey: "bcd374ecbd4d9f8f5b2cf25f12dc901b"

timeOutUpdate: 5
timeOutUpdatePerHour: 1