dataBase:
  dbHost: "127.0.0.1"
  dbPort: "5432"
  dbName: "exachange_rates"
  dbUser: "postgres"
  dbPassword: "7777777"

host:
  hostPort: ":8080"

apiKey: "14bf0c254b342edb4742253e3d60d821"
botApiKey: "6790196562:AAFezq6o9eZRyTrleY3xMbUvAsnaCPeVhc8"

timeOutUpdate: 5
timeOutUpdatePerHour: 1

